### ISSUE TITLE
"sortinghat export" adds additional whitespace to line endings in the created JSON file

### ISSUE THREAD

**Issue by aklapper** [grimoirelab/sortinghat#103]
The JSON File exported by `sortinghat export` adds a whitespace before any linebreak (`20 0A`) while the JSON database dump file provided by Bitergia's mordred/owlbot on github.com only has `0A`. 

This makes running `diff -pu` useless and creates misleading stats (`1 file changed, 71105 insertions(+), 5624 deletions(-)`).

**Comment by sduenas** [comment]
That's weird because, as far as I know, they use the same command. I'll check it!

**Comment by sduenas** [comment]
I couldn't reproduce this problem. When I run `sortinghat export`, there's no extra whitespace added. Which system are you using?

**Comment by aklapper** [comment]
Fedora 27 on x86_64, mariadb-10.2.9-3, python2-2.7.14-2, `sortinghat` pulled on 2017-11-21.

**Comment by sduenas** [comment]
Ok, I found the problem. It's related to Python 2.7 and to this bug report: https://hg.python.org/cpython/rev/78bad589f205. They say how to fix it in Python 2.7.

**Comment by sduenas** [comment]
@aklapper this bug is fixed in master
