### ISSUE TITLE
Add --no-strict-matching to gitdm2sh

### ISSUE THREAD

**Issue by acs** [grimoirelab/sortinghat#119]
In some cases the emails in gitdm are not complete. For example: custonsb@custonsb-desktop

This emails are the ones that are used in the git commits, so they will respected.

Right now gitdm2sh does not accept those emails:

```
(acs@dellx) /tmp $ gitdm2sh -a aliases.txt -e email-map.txt -d domain-map.txt -s "gitdm:cncf" -o cncf-gitdm.json
Error: line 6831: invalid email format: 'cusoinsb@cusoinsb-desktop'
```

gitdm2sh must support the same option that sorting in unify: 

```
--no-strict-matching  do not rigorous check of values (i.e, well formed
                        email addresses)
```

**Comment by sduenas** [comment]
This should be done as we did in #111
