### ISSUE TITLE
Source code to Python 3

### ISSUE THREAD

**Issue by sduenas** [grimoirelab/sortinghat#44]
Issue opened to track the status of this task. The idea is to port the code to Python 3 but keeping the compatibility with Python 2.7.

**Comment by gpoo** [comment]
what is your plan? Use a package like six or alike?

That is, to make it consistent with the other applications.

**Comment by sduenas** [comment]
Since I've been thinking on this, my idea has been always to support both versions on the same branch, without using 2to3 or having a fork to support Python 3.

That being said, I thought at first to use `six` or [python-future](http://python-future.org/) but I started following some tips and cheat sheets from different sites and then I realized, that for `sortinghat`, we didn't need these kind of packages. It just needs some imports from `__future__` and a few blocks checking which version of Python is running. The good of it is we don't need more dependencies to run the tool. The bad is that it messes the code up a little.

I have most of the code migrated and unit tests work on both versions. I'm performing some few tests more and then, I'll be able to upload the code. Then we can discuss if it is worthy to use `six` or dropping the 2.7 support.

**Comment by sduenas** [comment]
These is the full list of commits that I added to make the code compatible with Python 3. I'm not completely sure but I think it only works on Python >= 3.3.

* Misc
1c18929 - Add Python 3 support
4f61cad - Add Python 3 tests on TravisCI
97b4d6c - Update script to be compatible with Python 2/3

* Unicode/encoding/decoding issues
d61d3c8 - Fix encoding/decoding issues to support Python 2/3
847fffd - Fix error on not closed input file
b7137b9 - Fix not closed output file error
ddb8b94 - Update CSV reader to support Python 2/3 

* Syntax
ad713e8 - Update import statements to work on Python 2/3
d258f92 - Change absolute by relative imports
2f43ce5 - Change try..except blocks

* MySQL
4ac76c1 - Use PyMySQL driver when MySQLdb is not available
cc29a3b - Update caught exceptions
2d48020 -  Use MySQLdb driver by default on Python 2.7

**Comment by sduenas** [comment]
@andygrunwald What changes do we need make to have a Docker container for Python 3?

**Comment by andygrunwald** [comment]
@sduenas Just replace the line

```
FROM python:2.7
```
with
```
FROM python:3.4
```
(if you want to use Python 3.4). Choose `python:3.5.1` for v3.5.1 or `python:latest` for the latest version.
As you said >= Python 3.4 in your commits it make sense to pin it at v3.4.

See https://hub.docker.com/_/python/ for details.

Just a question: Is there any benefit from supporting both versions? Afaik all major OS have Python 3 alrready in, isn`t it?

**Comment by sduenas** [comment]
@andygrunwald  is it possible to include it on the same Dockerfile?

With regards to support both versions...I'd rather maintain Python 3 only, but for a first step I decided to keep both. If we see that everything works OK, we will remove it.

**Comment by andygrunwald** [comment]
@sduenas you can only chose one python version. Not both in a Dockerfile.
So just replace the `FROM` part as mentioned.

**Comment by andygrunwald** [comment]
@sduenas you can only chose one python version. Not both in a Dockerfile.
So just replace the `FROM` part as mentioned.

**Comment by jgbarah** [comment]
@sduenas Have in mind that, container-wise, doesn't make a lot of sense to use two different versions of Python, since what you usually want is a container "that works". So, you install (in this case) SortingHat, and just the version of Python you feel is better for making it work. If you want to have the two versions supported anyhow, probably the best thing to do would be having two containers, one with Python 2.x and another one with Python 3.x, so that people could deploy any of them, according to their preferences.
In case of maintaining only one, I agree with you on doing it with Python 3.x.

**Comment by andygrunwald** [comment]
:+1: to what @jgbarah said

**Comment by jgbarah** [comment]
Closing this one, since AFAIK, SortingHat works with Python3 since a long time ago.
