### ISSUE TITLE
Question:  does sortinghat get triggered by perceval and/or p2o.py?

### ISSUE THREAD

**Issue by robinmuilwijk** [grimoirelab/sortinghat#84]
Hi,

So far my metrics dashboard is based on grimoire-elk, perceval and kidash. I want to see if I can install sortinghat, and than of course use it. To better understand its workings, I have two questions:

1; what triggers sortinghat to collect data? I now load data into my indexes by running p2o.
2; can I show data from the sortinghat database on my dashboard, as this is obviously enriched data (by manual commands)?

Example: I use p2o commands to load commits and pull requests from GitHub. I do get some user data, like names, e-mail etc. My understanding is, that with sorthinghat I can manage these identities, and organisations. I could then better display data, which for example, would be linked to a single organisation.

**Comment by acs** [comment]
perceval does not use Sorting Hat at all.

p2o uses it during enrichment if selected. For that, pass the option:

`--db-sortinghat
`

with the name of the Sorting Hat database to use.

and for the database connection:

`--db-user --db-password --db-host --db-projects-map
`

**Comment by robinmuilwijk** [comment]
Thanks @acs I will give this a try.

**Comment by jgbarah** [comment]
Closing, since this seems answered... @robinmuilwijk please feel free to reopen if you feel that's convenient.
