### ISSUE TITLE
Difference between profile and identity?

### ISSUE THREAD

**Issue by robinmuilwijk** [grimoirelab/sortinghat#86]
I am about to setup sortinghat. I looked at all docs to get an idea on installation, configuration, and also usage.

What is the difference between profiles and (unique) identities? Is a profile the logic entity, that can contain more than one identity? For example an identity coming from GitHub data, and an identity coming from Jira data? And is only the profile shown on Kibana panels (through the enrichment step)?

**Comment by sduenas** [comment]
Hi @robinmuilwijk,

`Identity` is the entity where an identity from, for instance, GitHub, Jira, Git, IRC, is stored. These identities are always linked to a `Unique Identity` entity. This entity is only a hub to gather identities from different sources which are the same. Each `Unique Identity` has associated a profile and a set of enrollments.

The profile is only the VC card of that Unique Identity. It shows/stores the readable name associated to that identity. The profile is fully editable and you can store whatever you want on their fields. We use the profile to show on the Kibana panels a readable name for that unique identity.

**Comment by robinmuilwijk** [comment]
Thanks @sduenas ! That clarifies exactly what I was looking for to understand sortinghat a bit more.
